### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by daniel-wtd** [while-true-do/ansible-role-selinux#1]
### Type of Report

Review Request

### Actual behaviour

Role had no initial review.

### Expected behaviour

Role must be reviewed and commented.

**Comment by Cinux90** [comment]
- README.md:
travis svg not propper:
Currently: 
`[![Build Status](https://travis-ci.org/while-true-do/ansible-role-selinuxsvg?branch=master)](https://travis-ci.org/while-true-do/ansible-role-selinux)`

- should be:
`[![Build Status](https://travis-ci.org/while-true-do/ansible-role-selinux.svg?branch=master)](https://travis-ci.org/while-true-do/ansible-role-selinux)`

Short: the dot before svg is missing

- folder files and vars are empty -> can be deleted from my side
- maybe also template folder

**Comment by daniel-wtd** [comment]
thanks a lot, all addressed in #2
